/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Ward Api
 * Hospital Ward management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xpaucof@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Bed,
} from '../models';
import {
    BedFromJSON,
    BedToJSON,
} from '../models';

export interface CreateBedRequest {
    wardId: string;
    bed: Bed;
}

export interface DeleteBedRequest {
    wardId: string;
    bedId: string;
}

export interface GetBedRequest {
    wardId: string;
    bedId: string;
}

export interface GetBedsRequest {
    wardId: string;
}

export interface UpdateBedRequest {
    wardId: string;
    bedId: string;
    bed: Bed;
}

/**
 * BedsApi - interface
 * 
 * @export
 * @interface BedsApiInterface
 */
export interface BedsApiInterface {
    /**
     * 
     * @summary Creates a new bed in a ward
     * @param {string} wardId 
     * @param {Bed} bed 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BedsApiInterface
     */
    createBedRaw(requestParameters: CreateBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bed>>;

    /**
     * Creates a new bed in a ward
     */
    createBed(requestParameters: CreateBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bed>;

    /**
     * 
     * @summary Deletes a specific bed
     * @param {string} wardId 
     * @param {string} bedId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BedsApiInterface
     */
    deleteBedRaw(requestParameters: DeleteBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Deletes a specific bed
     */
    deleteBed(requestParameters: DeleteBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Provides details about a bed
     * @param {string} wardId 
     * @param {string} bedId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BedsApiInterface
     */
    getBedRaw(requestParameters: GetBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bed>>;

    /**
     * Provides details about a bed
     */
    getBed(requestParameters: GetBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bed>;

    /**
     * 
     * @summary Provides the list of beds for a ward
     * @param {string} wardId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BedsApiInterface
     */
    getBedsRaw(requestParameters: GetBedsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Bed>>>;

    /**
     * Provides the list of beds for a ward
     */
    getBeds(requestParameters: GetBedsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Bed>>;

    /**
     * 
     * @summary Updates a specific bed
     * @param {string} wardId 
     * @param {string} bedId 
     * @param {Bed} bed 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BedsApiInterface
     */
    updateBedRaw(requestParameters: UpdateBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bed>>;

    /**
     * Updates a specific bed
     */
    updateBed(requestParameters: UpdateBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bed>;

}

/**
 * 
 */
export class BedsApi extends runtime.BaseAPI implements BedsApiInterface {

    /**
     * Creates a new bed in a ward
     */
    async createBedRaw(requestParameters: CreateBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bed>> {
        if (requestParameters.wardId === null || requestParameters.wardId === undefined) {
            throw new runtime.RequiredError('wardId','Required parameter requestParameters.wardId was null or undefined when calling createBed.');
        }

        if (requestParameters.bed === null || requestParameters.bed === undefined) {
            throw new runtime.RequiredError('bed','Required parameter requestParameters.bed was null or undefined when calling createBed.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/ward/{wardId}/beds`.replace(`{${"wardId"}}`, encodeURIComponent(String(requestParameters.wardId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BedToJSON(requestParameters.bed),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BedFromJSON(jsonValue));
    }

    /**
     * Creates a new bed in a ward
     */
    async createBed(requestParameters: CreateBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bed> {
        const response = await this.createBedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a specific bed
     */
    async deleteBedRaw(requestParameters: DeleteBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.wardId === null || requestParameters.wardId === undefined) {
            throw new runtime.RequiredError('wardId','Required parameter requestParameters.wardId was null or undefined when calling deleteBed.');
        }

        if (requestParameters.bedId === null || requestParameters.bedId === undefined) {
            throw new runtime.RequiredError('bedId','Required parameter requestParameters.bedId was null or undefined when calling deleteBed.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ward/{wardId}/beds/{bedId}`.replace(`{${"wardId"}}`, encodeURIComponent(String(requestParameters.wardId))).replace(`{${"bedId"}}`, encodeURIComponent(String(requestParameters.bedId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a specific bed
     */
    async deleteBed(requestParameters: DeleteBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBedRaw(requestParameters, initOverrides);
    }

    /**
     * Provides details about a bed
     */
    async getBedRaw(requestParameters: GetBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bed>> {
        if (requestParameters.wardId === null || requestParameters.wardId === undefined) {
            throw new runtime.RequiredError('wardId','Required parameter requestParameters.wardId was null or undefined when calling getBed.');
        }

        if (requestParameters.bedId === null || requestParameters.bedId === undefined) {
            throw new runtime.RequiredError('bedId','Required parameter requestParameters.bedId was null or undefined when calling getBed.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ward/{wardId}/beds/{bedId}`.replace(`{${"wardId"}}`, encodeURIComponent(String(requestParameters.wardId))).replace(`{${"bedId"}}`, encodeURIComponent(String(requestParameters.bedId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BedFromJSON(jsonValue));
    }

    /**
     * Provides details about a bed
     */
    async getBed(requestParameters: GetBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bed> {
        const response = await this.getBedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Provides the list of beds for a ward
     */
    async getBedsRaw(requestParameters: GetBedsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Bed>>> {
        if (requestParameters.wardId === null || requestParameters.wardId === undefined) {
            throw new runtime.RequiredError('wardId','Required parameter requestParameters.wardId was null or undefined when calling getBeds.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ward/{wardId}/beds`.replace(`{${"wardId"}}`, encodeURIComponent(String(requestParameters.wardId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BedFromJSON));
    }

    /**
     * Provides the list of beds for a ward
     */
    async getBeds(requestParameters: GetBedsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Bed>> {
        const response = await this.getBedsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a specific bed
     */
    async updateBedRaw(requestParameters: UpdateBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bed>> {
        if (requestParameters.wardId === null || requestParameters.wardId === undefined) {
            throw new runtime.RequiredError('wardId','Required parameter requestParameters.wardId was null or undefined when calling updateBed.');
        }

        if (requestParameters.bedId === null || requestParameters.bedId === undefined) {
            throw new runtime.RequiredError('bedId','Required parameter requestParameters.bedId was null or undefined when calling updateBed.');
        }

        if (requestParameters.bed === null || requestParameters.bed === undefined) {
            throw new runtime.RequiredError('bed','Required parameter requestParameters.bed was null or undefined when calling updateBed.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/ward/{wardId}/beds/{bedId}`.replace(`{${"wardId"}}`, encodeURIComponent(String(requestParameters.wardId))).replace(`{${"bedId"}}`, encodeURIComponent(String(requestParameters.bedId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BedToJSON(requestParameters.bed),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BedFromJSON(jsonValue));
    }

    /**
     * Updates a specific bed
     */
    async updateBed(requestParameters: UpdateBedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bed> {
        const response = await this.updateBedRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
