/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Ward Api
 * Hospital Ward management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xpaucof@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Visit,
} from '../models';
import {
    VisitFromJSON,
    VisitToJSON,
} from '../models';

export interface CreateVisitRequest {
    wardId: string;
    visit: Visit;
}

export interface DeleteVisitRequest {
    wardId: string;
    visitId: string;
}

export interface GetVisitRequest {
    wardId: string;
    visitId: string;
}

export interface GetVisitsRequest {
    wardId: string;
}

export interface UpdateVisitRequest {
    wardId: string;
    visitId: string;
    visit: Visit;
}

/**
 * VisitsApi - interface
 * 
 * @export
 * @interface VisitsApiInterface
 */
export interface VisitsApiInterface {
    /**
     * 
     * @summary Creates a new visit for a ward
     * @param {string} wardId 
     * @param {Visit} visit 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VisitsApiInterface
     */
    createVisitRaw(requestParameters: CreateVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Visit>>;

    /**
     * Creates a new visit for a ward
     */
    createVisit(requestParameters: CreateVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Visit>;

    /**
     * 
     * @summary Deletes a specific visit
     * @param {string} wardId 
     * @param {string} visitId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VisitsApiInterface
     */
    deleteVisitRaw(requestParameters: DeleteVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Deletes a specific visit
     */
    deleteVisit(requestParameters: DeleteVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Provides details about a visit
     * @param {string} wardId 
     * @param {string} visitId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VisitsApiInterface
     */
    getVisitRaw(requestParameters: GetVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Visit>>;

    /**
     * Provides details about a visit
     */
    getVisit(requestParameters: GetVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Visit>;

    /**
     * 
     * @summary Provides the list of visits for a ward
     * @param {string} wardId pass the id of the particular ward
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VisitsApiInterface
     */
    getVisitsRaw(requestParameters: GetVisitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Visit>>>;

    /**
     * Provides the list of visits for a ward
     */
    getVisits(requestParameters: GetVisitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Visit>>;

    /**
     * 
     * @summary Updates a specific visit
     * @param {string} wardId 
     * @param {string} visitId 
     * @param {Visit} visit 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VisitsApiInterface
     */
    updateVisitRaw(requestParameters: UpdateVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Visit>>;

    /**
     * Updates a specific visit
     */
    updateVisit(requestParameters: UpdateVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Visit>;

}

/**
 * 
 */
export class VisitsApi extends runtime.BaseAPI implements VisitsApiInterface {

    /**
     * Creates a new visit for a ward
     */
    async createVisitRaw(requestParameters: CreateVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Visit>> {
        if (requestParameters.wardId === null || requestParameters.wardId === undefined) {
            throw new runtime.RequiredError('wardId','Required parameter requestParameters.wardId was null or undefined when calling createVisit.');
        }

        if (requestParameters.visit === null || requestParameters.visit === undefined) {
            throw new runtime.RequiredError('visit','Required parameter requestParameters.visit was null or undefined when calling createVisit.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/ward/{wardId}/visits`.replace(`{${"wardId"}}`, encodeURIComponent(String(requestParameters.wardId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VisitToJSON(requestParameters.visit),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VisitFromJSON(jsonValue));
    }

    /**
     * Creates a new visit for a ward
     */
    async createVisit(requestParameters: CreateVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Visit> {
        const response = await this.createVisitRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a specific visit
     */
    async deleteVisitRaw(requestParameters: DeleteVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.wardId === null || requestParameters.wardId === undefined) {
            throw new runtime.RequiredError('wardId','Required parameter requestParameters.wardId was null or undefined when calling deleteVisit.');
        }

        if (requestParameters.visitId === null || requestParameters.visitId === undefined) {
            throw new runtime.RequiredError('visitId','Required parameter requestParameters.visitId was null or undefined when calling deleteVisit.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ward/{wardId}/visits/{visitId}`.replace(`{${"wardId"}}`, encodeURIComponent(String(requestParameters.wardId))).replace(`{${"visitId"}}`, encodeURIComponent(String(requestParameters.visitId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a specific visit
     */
    async deleteVisit(requestParameters: DeleteVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteVisitRaw(requestParameters, initOverrides);
    }

    /**
     * Provides details about a visit
     */
    async getVisitRaw(requestParameters: GetVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Visit>> {
        if (requestParameters.wardId === null || requestParameters.wardId === undefined) {
            throw new runtime.RequiredError('wardId','Required parameter requestParameters.wardId was null or undefined when calling getVisit.');
        }

        if (requestParameters.visitId === null || requestParameters.visitId === undefined) {
            throw new runtime.RequiredError('visitId','Required parameter requestParameters.visitId was null or undefined when calling getVisit.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ward/{wardId}/visits/{visitId}`.replace(`{${"wardId"}}`, encodeURIComponent(String(requestParameters.wardId))).replace(`{${"visitId"}}`, encodeURIComponent(String(requestParameters.visitId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VisitFromJSON(jsonValue));
    }

    /**
     * Provides details about a visit
     */
    async getVisit(requestParameters: GetVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Visit> {
        const response = await this.getVisitRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Provides the list of visits for a ward
     */
    async getVisitsRaw(requestParameters: GetVisitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Visit>>> {
        if (requestParameters.wardId === null || requestParameters.wardId === undefined) {
            throw new runtime.RequiredError('wardId','Required parameter requestParameters.wardId was null or undefined when calling getVisits.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ward/{wardId}/visits`.replace(`{${"wardId"}}`, encodeURIComponent(String(requestParameters.wardId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VisitFromJSON));
    }

    /**
     * Provides the list of visits for a ward
     */
    async getVisits(requestParameters: GetVisitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Visit>> {
        const response = await this.getVisitsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a specific visit
     */
    async updateVisitRaw(requestParameters: UpdateVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Visit>> {
        if (requestParameters.wardId === null || requestParameters.wardId === undefined) {
            throw new runtime.RequiredError('wardId','Required parameter requestParameters.wardId was null or undefined when calling updateVisit.');
        }

        if (requestParameters.visitId === null || requestParameters.visitId === undefined) {
            throw new runtime.RequiredError('visitId','Required parameter requestParameters.visitId was null or undefined when calling updateVisit.');
        }

        if (requestParameters.visit === null || requestParameters.visit === undefined) {
            throw new runtime.RequiredError('visit','Required parameter requestParameters.visit was null or undefined when calling updateVisit.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/ward/{wardId}/visits/{visitId}`.replace(`{${"wardId"}}`, encodeURIComponent(String(requestParameters.wardId))).replace(`{${"visitId"}}`, encodeURIComponent(String(requestParameters.visitId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: VisitToJSON(requestParameters.visit),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VisitFromJSON(jsonValue));
    }

    /**
     * Updates a specific visit
     */
    async updateVisit(requestParameters: UpdateVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Visit> {
        const response = await this.updateVisitRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
