/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Ward Api
 * Hospital Ward management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xpaucof@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Bed
 */
export interface Bed {
    /**
     * Unique id of the bed
     * @type {string}
     * @memberof Bed
     */
    id: string;
    /**
     * Bed/room number
     * @type {string}
     * @memberof Bed
     */
    number: string;
    /**
     * Current status of the bed
     * @type {string}
     * @memberof Bed
     */
    status: BedStatusEnum;
    /**
     * ID of the patient currently in the bed (if occupied)
     * @type {string}
     * @memberof Bed
     */
    patientId?: string;
}


/**
 * @export
 */
export const BedStatusEnum = {
    Free: 'free',
    Occupied: 'occupied',
    OutOfService: 'out-of-service'
} as const;
export type BedStatusEnum = typeof BedStatusEnum[keyof typeof BedStatusEnum];


/**
 * Check if a given object implements the Bed interface.
 */
export function instanceOfBed(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "number" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function BedFromJSON(json: any): Bed {
    return BedFromJSONTyped(json, false);
}

export function BedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'number': json['number'],
        'status': json['status'],
        'patientId': !exists(json, 'patientId') ? undefined : json['patientId'],
    };
}

export function BedToJSON(value?: Bed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'number': value.number,
        'status': value.status,
        'patientId': value.patientId,
    };
}

