/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Ward Api
 * Hospital Ward management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xpaucof@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Visit
 */
export interface Visit {
    /**
     * Unique id of the visit
     * @type {string}
     * @memberof Visit
     */
    id: string;
    /**
     * Unique identifier of the patient
     * @type {string}
     * @memberof Visit
     */
    patientId: string;
    /**
     * Unique identifier of the bed where visit took place
     * @type {string}
     * @memberof Visit
     */
    bedId: string;
    /**
     * Date of the visit
     * @type {string}
     * @memberof Visit
     */
    date: string;
    /**
     * Time of the visit (HH:MM)
     * @type {string}
     * @memberof Visit
     */
    time: string;
    /**
     * List of attending doctors
     * @type {Array<string>}
     * @memberof Visit
     */
    doctors?: Array<string>;
    /**
     * Clinical notes from the visit
     * @type {string}
     * @memberof Visit
     */
    clinicalNotes?: string;
}

/**
 * Check if a given object implements the Visit interface.
 */
export function instanceOfVisit(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "patientId" in value;
    isInstance = isInstance && "bedId" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "time" in value;

    return isInstance;
}

export function VisitFromJSON(json: any): Visit {
    return VisitFromJSONTyped(json, false);
}

export function VisitFromJSONTyped(json: any, ignoreDiscriminator: boolean): Visit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'patientId': json['patientId'],
        'bedId': json['bedId'],
        'date': json['date'],
        'time': json['time'],
        'doctors': !exists(json, 'doctors') ? undefined : json['doctors'],
        'clinicalNotes': !exists(json, 'clinicalNotes') ? undefined : json['clinicalNotes'],
    };
}

export function VisitToJSON(value?: Visit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return value;
    }
    return {
        
        'id': value.id,
        'patientId': value.patientId,
        'bedId': value.bedId,
        'date': value.date,
        'time': value.time,
        'doctors': value.doctors,
        'clinicalNotes': value.clinicalNotes,
    };
}

