/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Ward Api
 * Hospital Ward management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xpaucof@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Bed } from './Bed';
import {
    BedFromJSON,
    BedFromJSONTyped,
    BedToJSON,
} from './Bed';
import type { Visit } from './Visit';
import {
    VisitFromJSON,
    VisitFromJSONTyped,
    VisitToJSON,
} from './Visit';

/**
 * 
 * @export
 * @interface Ward
 */
export interface Ward {
    /**
     * Unique identifier of the ward
     * @type {string}
     * @memberof Ward
     */
    id: string;
    /**
     * Human readable name of the ward
     * @type {string}
     * @memberof Ward
     */
    name: string;
    /**
     * 
     * @type {Array<Visit>}
     * @memberof Ward
     */
    visits?: Array<Visit>;
    /**
     * 
     * @type {Array<Bed>}
     * @memberof Ward
     */
    beds?: Array<Bed>;
}

/**
 * Check if a given object implements the Ward interface.
 */
export function instanceOfWard(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function WardFromJSON(json: any): Ward {
    return WardFromJSONTyped(json, false);
}

export function WardFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ward {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'visits': !exists(json, 'visits') ? undefined : ((json['visits'] as Array<any>).map(VisitFromJSON)),
        'beds': !exists(json, 'beds') ? undefined : ((json['beds'] as Array<any>).map(BedFromJSON)),
    };
}

export function WardToJSON(value?: Ward | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'visits': value.visits === undefined ? undefined : ((value.visits as Array<any>).map(VisitToJSON)),
        'beds': value.beds === undefined ? undefined : ((value.beds as Array<any>).map(BedToJSON)),
    };
}

