/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XmesiarikovaBedApp {
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
        "wardId": string;
    }
    interface XmesiarikovaBedEditor {
        "apiBase": string;
        "bedId": string;
        "wardId": string;
    }
    interface XmesiarikovaBedList {
        "apiBase": string;
        "wardId": string;
    }
    interface XpaucofVisitApp {
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
        "wardId": string;
    }
    interface XpaucofVisitEditor {
        "apiBase": string;
        "visitId": string;
        "wardId": string;
    }
    interface XpaucofVisitList {
        "apiBase": string;
        "wardId": string;
    }
}
export interface XmesiarikovaBedEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXmesiarikovaBedEditorElement;
}
export interface XmesiarikovaBedListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXmesiarikovaBedListElement;
}
export interface XpaucofVisitEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXpaucofVisitEditorElement;
}
export interface XpaucofVisitListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXpaucofVisitListElement;
}
declare global {
    interface HTMLXmesiarikovaBedAppElement extends Components.XmesiarikovaBedApp, HTMLStencilElement {
    }
    var HTMLXmesiarikovaBedAppElement: {
        prototype: HTMLXmesiarikovaBedAppElement;
        new (): HTMLXmesiarikovaBedAppElement;
    };
    interface HTMLXmesiarikovaBedEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLXmesiarikovaBedEditorElement extends Components.XmesiarikovaBedEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXmesiarikovaBedEditorElementEventMap>(type: K, listener: (this: HTMLXmesiarikovaBedEditorElement, ev: XmesiarikovaBedEditorCustomEvent<HTMLXmesiarikovaBedEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXmesiarikovaBedEditorElementEventMap>(type: K, listener: (this: HTMLXmesiarikovaBedEditorElement, ev: XmesiarikovaBedEditorCustomEvent<HTMLXmesiarikovaBedEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXmesiarikovaBedEditorElement: {
        prototype: HTMLXmesiarikovaBedEditorElement;
        new (): HTMLXmesiarikovaBedEditorElement;
    };
    interface HTMLXmesiarikovaBedListElementEventMap {
        "bed-clicked": string;
    }
    interface HTMLXmesiarikovaBedListElement extends Components.XmesiarikovaBedList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXmesiarikovaBedListElementEventMap>(type: K, listener: (this: HTMLXmesiarikovaBedListElement, ev: XmesiarikovaBedListCustomEvent<HTMLXmesiarikovaBedListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXmesiarikovaBedListElementEventMap>(type: K, listener: (this: HTMLXmesiarikovaBedListElement, ev: XmesiarikovaBedListCustomEvent<HTMLXmesiarikovaBedListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXmesiarikovaBedListElement: {
        prototype: HTMLXmesiarikovaBedListElement;
        new (): HTMLXmesiarikovaBedListElement;
    };
    interface HTMLXpaucofVisitAppElement extends Components.XpaucofVisitApp, HTMLStencilElement {
    }
    var HTMLXpaucofVisitAppElement: {
        prototype: HTMLXpaucofVisitAppElement;
        new (): HTMLXpaucofVisitAppElement;
    };
    interface HTMLXpaucofVisitEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLXpaucofVisitEditorElement extends Components.XpaucofVisitEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXpaucofVisitEditorElementEventMap>(type: K, listener: (this: HTMLXpaucofVisitEditorElement, ev: XpaucofVisitEditorCustomEvent<HTMLXpaucofVisitEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXpaucofVisitEditorElementEventMap>(type: K, listener: (this: HTMLXpaucofVisitEditorElement, ev: XpaucofVisitEditorCustomEvent<HTMLXpaucofVisitEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXpaucofVisitEditorElement: {
        prototype: HTMLXpaucofVisitEditorElement;
        new (): HTMLXpaucofVisitEditorElement;
    };
    interface HTMLXpaucofVisitListElementEventMap {
        "visit-clicked": string;
    }
    interface HTMLXpaucofVisitListElement extends Components.XpaucofVisitList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXpaucofVisitListElementEventMap>(type: K, listener: (this: HTMLXpaucofVisitListElement, ev: XpaucofVisitListCustomEvent<HTMLXpaucofVisitListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXpaucofVisitListElementEventMap>(type: K, listener: (this: HTMLXpaucofVisitListElement, ev: XpaucofVisitListCustomEvent<HTMLXpaucofVisitListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXpaucofVisitListElement: {
        prototype: HTMLXpaucofVisitListElement;
        new (): HTMLXpaucofVisitListElement;
    };
    interface HTMLElementTagNameMap {
        "xmesiarikova-bed-app": HTMLXmesiarikovaBedAppElement;
        "xmesiarikova-bed-editor": HTMLXmesiarikovaBedEditorElement;
        "xmesiarikova-bed-list": HTMLXmesiarikovaBedListElement;
        "xpaucof-visit-app": HTMLXpaucofVisitAppElement;
        "xpaucof-visit-editor": HTMLXpaucofVisitEditorElement;
        "xpaucof-visit-list": HTMLXpaucofVisitListElement;
    }
}
declare namespace LocalJSX {
    interface XmesiarikovaBedApp {
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
        "wardId"?: string;
    }
    interface XmesiarikovaBedEditor {
        "apiBase"?: string;
        "bedId"?: string;
        "onEditor-closed"?: (event: XmesiarikovaBedEditorCustomEvent<string>) => void;
        "wardId"?: string;
    }
    interface XmesiarikovaBedList {
        "apiBase"?: string;
        "onBed-clicked"?: (event: XmesiarikovaBedListCustomEvent<string>) => void;
        "wardId"?: string;
    }
    interface XpaucofVisitApp {
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
        "wardId"?: string;
    }
    interface XpaucofVisitEditor {
        "apiBase"?: string;
        "onEditor-closed"?: (event: XpaucofVisitEditorCustomEvent<string>) => void;
        "visitId"?: string;
        "wardId"?: string;
    }
    interface XpaucofVisitList {
        "apiBase"?: string;
        "onVisit-clicked"?: (event: XpaucofVisitListCustomEvent<string>) => void;
        "wardId"?: string;
    }

    interface XmesiarikovaBedAppAttributes {
        "basePath": string;
        "apiBase": string;
        "wardId": string;
    }
    interface XmesiarikovaBedEditorAttributes {
        "bedId": string;
        "wardId": string;
        "apiBase": string;
    }
    interface XmesiarikovaBedListAttributes {
        "apiBase": string;
        "wardId": string;
    }
    interface XpaucofVisitAppAttributes {
        "basePath": string;
        "apiBase": string;
        "wardId": string;
    }
    interface XpaucofVisitEditorAttributes {
        "visitId": string;
        "wardId": string;
        "apiBase": string;
    }
    interface XpaucofVisitListAttributes {
        "apiBase": string;
        "wardId": string;
    }

    interface IntrinsicElements {
        "xmesiarikova-bed-app": Omit<XmesiarikovaBedApp, keyof XmesiarikovaBedAppAttributes> & { [K in keyof XmesiarikovaBedApp & keyof XmesiarikovaBedAppAttributes]?: XmesiarikovaBedApp[K] } & { [K in keyof XmesiarikovaBedApp & keyof XmesiarikovaBedAppAttributes as `attr:${K}`]?: XmesiarikovaBedAppAttributes[K] } & { [K in keyof XmesiarikovaBedApp & keyof XmesiarikovaBedAppAttributes as `prop:${K}`]?: XmesiarikovaBedApp[K] };
        "xmesiarikova-bed-editor": Omit<XmesiarikovaBedEditor, keyof XmesiarikovaBedEditorAttributes> & { [K in keyof XmesiarikovaBedEditor & keyof XmesiarikovaBedEditorAttributes]?: XmesiarikovaBedEditor[K] } & { [K in keyof XmesiarikovaBedEditor & keyof XmesiarikovaBedEditorAttributes as `attr:${K}`]?: XmesiarikovaBedEditorAttributes[K] } & { [K in keyof XmesiarikovaBedEditor & keyof XmesiarikovaBedEditorAttributes as `prop:${K}`]?: XmesiarikovaBedEditor[K] };
        "xmesiarikova-bed-list": Omit<XmesiarikovaBedList, keyof XmesiarikovaBedListAttributes> & { [K in keyof XmesiarikovaBedList & keyof XmesiarikovaBedListAttributes]?: XmesiarikovaBedList[K] } & { [K in keyof XmesiarikovaBedList & keyof XmesiarikovaBedListAttributes as `attr:${K}`]?: XmesiarikovaBedListAttributes[K] } & { [K in keyof XmesiarikovaBedList & keyof XmesiarikovaBedListAttributes as `prop:${K}`]?: XmesiarikovaBedList[K] };
        "xpaucof-visit-app": Omit<XpaucofVisitApp, keyof XpaucofVisitAppAttributes> & { [K in keyof XpaucofVisitApp & keyof XpaucofVisitAppAttributes]?: XpaucofVisitApp[K] } & { [K in keyof XpaucofVisitApp & keyof XpaucofVisitAppAttributes as `attr:${K}`]?: XpaucofVisitAppAttributes[K] } & { [K in keyof XpaucofVisitApp & keyof XpaucofVisitAppAttributes as `prop:${K}`]?: XpaucofVisitApp[K] };
        "xpaucof-visit-editor": Omit<XpaucofVisitEditor, keyof XpaucofVisitEditorAttributes> & { [K in keyof XpaucofVisitEditor & keyof XpaucofVisitEditorAttributes]?: XpaucofVisitEditor[K] } & { [K in keyof XpaucofVisitEditor & keyof XpaucofVisitEditorAttributes as `attr:${K}`]?: XpaucofVisitEditorAttributes[K] } & { [K in keyof XpaucofVisitEditor & keyof XpaucofVisitEditorAttributes as `prop:${K}`]?: XpaucofVisitEditor[K] };
        "xpaucof-visit-list": Omit<XpaucofVisitList, keyof XpaucofVisitListAttributes> & { [K in keyof XpaucofVisitList & keyof XpaucofVisitListAttributes]?: XpaucofVisitList[K] } & { [K in keyof XpaucofVisitList & keyof XpaucofVisitListAttributes as `attr:${K}`]?: XpaucofVisitListAttributes[K] } & { [K in keyof XpaucofVisitList & keyof XpaucofVisitListAttributes as `prop:${K}`]?: XpaucofVisitList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xmesiarikova-bed-app": LocalJSX.IntrinsicElements["xmesiarikova-bed-app"] & JSXBase.HTMLAttributes<HTMLXmesiarikovaBedAppElement>;
            "xmesiarikova-bed-editor": LocalJSX.IntrinsicElements["xmesiarikova-bed-editor"] & JSXBase.HTMLAttributes<HTMLXmesiarikovaBedEditorElement>;
            "xmesiarikova-bed-list": LocalJSX.IntrinsicElements["xmesiarikova-bed-list"] & JSXBase.HTMLAttributes<HTMLXmesiarikovaBedListElement>;
            "xpaucof-visit-app": LocalJSX.IntrinsicElements["xpaucof-visit-app"] & JSXBase.HTMLAttributes<HTMLXpaucofVisitAppElement>;
            "xpaucof-visit-editor": LocalJSX.IntrinsicElements["xpaucof-visit-editor"] & JSXBase.HTMLAttributes<HTMLXpaucofVisitEditorElement>;
            "xpaucof-visit-list": LocalJSX.IntrinsicElements["xpaucof-visit-list"] & JSXBase.HTMLAttributes<HTMLXpaucofVisitListElement>;
        }
    }
}
