/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XmasiarikovaBedApp {
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
        "wardId": string;
    }
    interface XmasiarikovaBedEditor {
        "apiBase": string;
        "bedId": string;
        "wardId": string;
    }
    interface XmasiarikovaBedList {
        "apiBase": string;
        "wardId": string;
    }
    interface XpaucofHospitalApp {
        /**
          * @default ''
         */
        "basePath": string;
        "bedApiBase": string;
        "visitApiBase": string;
        "wardId": string;
    }
    interface XpaucofVisitApp {
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
        "wardId": string;
    }
    interface XpaucofVisitEditor {
        "apiBase"?: string;
        "visitId"?: string;
        "wardId"?: string;
    }
    interface XpaucofVisitList {
        "apiBase"?: string;
        "wardId"?: string;
    }
}
export interface XmasiarikovaBedEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXmasiarikovaBedEditorElement;
}
export interface XmasiarikovaBedListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXmasiarikovaBedListElement;
}
export interface XpaucofVisitEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXpaucofVisitEditorElement;
}
export interface XpaucofVisitListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXpaucofVisitListElement;
}
declare global {
    interface HTMLXmasiarikovaBedAppElement extends Components.XmasiarikovaBedApp, HTMLStencilElement {
    }
    var HTMLXmasiarikovaBedAppElement: {
        prototype: HTMLXmasiarikovaBedAppElement;
        new (): HTMLXmasiarikovaBedAppElement;
    };
    interface HTMLXmasiarikovaBedEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLXmasiarikovaBedEditorElement extends Components.XmasiarikovaBedEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXmasiarikovaBedEditorElementEventMap>(type: K, listener: (this: HTMLXmasiarikovaBedEditorElement, ev: XmasiarikovaBedEditorCustomEvent<HTMLXmasiarikovaBedEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXmasiarikovaBedEditorElementEventMap>(type: K, listener: (this: HTMLXmasiarikovaBedEditorElement, ev: XmasiarikovaBedEditorCustomEvent<HTMLXmasiarikovaBedEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXmasiarikovaBedEditorElement: {
        prototype: HTMLXmasiarikovaBedEditorElement;
        new (): HTMLXmasiarikovaBedEditorElement;
    };
    interface HTMLXmasiarikovaBedListElementEventMap {
        "bed-clicked": string;
    }
    interface HTMLXmasiarikovaBedListElement extends Components.XmasiarikovaBedList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXmasiarikovaBedListElementEventMap>(type: K, listener: (this: HTMLXmasiarikovaBedListElement, ev: XmasiarikovaBedListCustomEvent<HTMLXmasiarikovaBedListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXmasiarikovaBedListElementEventMap>(type: K, listener: (this: HTMLXmasiarikovaBedListElement, ev: XmasiarikovaBedListCustomEvent<HTMLXmasiarikovaBedListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXmasiarikovaBedListElement: {
        prototype: HTMLXmasiarikovaBedListElement;
        new (): HTMLXmasiarikovaBedListElement;
    };
    interface HTMLXpaucofHospitalAppElement extends Components.XpaucofHospitalApp, HTMLStencilElement {
    }
    var HTMLXpaucofHospitalAppElement: {
        prototype: HTMLXpaucofHospitalAppElement;
        new (): HTMLXpaucofHospitalAppElement;
    };
    interface HTMLXpaucofVisitAppElement extends Components.XpaucofVisitApp, HTMLStencilElement {
    }
    var HTMLXpaucofVisitAppElement: {
        prototype: HTMLXpaucofVisitAppElement;
        new (): HTMLXpaucofVisitAppElement;
    };
    interface HTMLXpaucofVisitEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLXpaucofVisitEditorElement extends Components.XpaucofVisitEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXpaucofVisitEditorElementEventMap>(type: K, listener: (this: HTMLXpaucofVisitEditorElement, ev: XpaucofVisitEditorCustomEvent<HTMLXpaucofVisitEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXpaucofVisitEditorElementEventMap>(type: K, listener: (this: HTMLXpaucofVisitEditorElement, ev: XpaucofVisitEditorCustomEvent<HTMLXpaucofVisitEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXpaucofVisitEditorElement: {
        prototype: HTMLXpaucofVisitEditorElement;
        new (): HTMLXpaucofVisitEditorElement;
    };
    interface HTMLXpaucofVisitListElementEventMap {
        "visit-clicked": string;
    }
    interface HTMLXpaucofVisitListElement extends Components.XpaucofVisitList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXpaucofVisitListElementEventMap>(type: K, listener: (this: HTMLXpaucofVisitListElement, ev: XpaucofVisitListCustomEvent<HTMLXpaucofVisitListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXpaucofVisitListElementEventMap>(type: K, listener: (this: HTMLXpaucofVisitListElement, ev: XpaucofVisitListCustomEvent<HTMLXpaucofVisitListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXpaucofVisitListElement: {
        prototype: HTMLXpaucofVisitListElement;
        new (): HTMLXpaucofVisitListElement;
    };
    interface HTMLElementTagNameMap {
        "xmasiarikova-bed-app": HTMLXmasiarikovaBedAppElement;
        "xmasiarikova-bed-editor": HTMLXmasiarikovaBedEditorElement;
        "xmasiarikova-bed-list": HTMLXmasiarikovaBedListElement;
        "xpaucof-hospital-app": HTMLXpaucofHospitalAppElement;
        "xpaucof-visit-app": HTMLXpaucofVisitAppElement;
        "xpaucof-visit-editor": HTMLXpaucofVisitEditorElement;
        "xpaucof-visit-list": HTMLXpaucofVisitListElement;
    }
}
declare namespace LocalJSX {
    interface XmasiarikovaBedApp {
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
        "wardId"?: string;
    }
    interface XmasiarikovaBedEditor {
        "apiBase"?: string;
        "bedId"?: string;
        "onEditor-closed"?: (event: XmasiarikovaBedEditorCustomEvent<string>) => void;
        "wardId"?: string;
    }
    interface XmasiarikovaBedList {
        "apiBase"?: string;
        "onBed-clicked"?: (event: XmasiarikovaBedListCustomEvent<string>) => void;
        "wardId"?: string;
    }
    interface XpaucofHospitalApp {
        /**
          * @default ''
         */
        "basePath"?: string;
        "bedApiBase"?: string;
        "visitApiBase"?: string;
        "wardId"?: string;
    }
    interface XpaucofVisitApp {
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
        "wardId"?: string;
    }
    interface XpaucofVisitEditor {
        "apiBase"?: string;
        "onEditor-closed"?: (event: XpaucofVisitEditorCustomEvent<string>) => void;
        "visitId"?: string;
        "wardId"?: string;
    }
    interface XpaucofVisitList {
        "apiBase"?: string;
        "onVisit-clicked"?: (event: XpaucofVisitListCustomEvent<string>) => void;
        "wardId"?: string;
    }

    interface XmasiarikovaBedAppAttributes {
        "basePath": string;
        "apiBase": string;
        "wardId": string;
    }
    interface XmasiarikovaBedEditorAttributes {
        "bedId": string;
        "wardId": string;
        "apiBase": string;
    }
    interface XmasiarikovaBedListAttributes {
        "apiBase": string;
        "wardId": string;
    }
    interface XpaucofHospitalAppAttributes {
        "visitApiBase": string;
        "bedApiBase": string;
        "wardId": string;
        "basePath": string;
    }
    interface XpaucofVisitAppAttributes {
        "basePath": string;
        "apiBase": string;
        "wardId": string;
    }
    interface XpaucofVisitEditorAttributes {
        "visitId": string;
        "wardId": string;
        "apiBase": string;
    }
    interface XpaucofVisitListAttributes {
        "apiBase": string;
        "wardId": string;
    }

    interface IntrinsicElements {
        "xmasiarikova-bed-app": Omit<XmasiarikovaBedApp, keyof XmasiarikovaBedAppAttributes> & { [K in keyof XmasiarikovaBedApp & keyof XmasiarikovaBedAppAttributes]?: XmasiarikovaBedApp[K] } & { [K in keyof XmasiarikovaBedApp & keyof XmasiarikovaBedAppAttributes as `attr:${K}`]?: XmasiarikovaBedAppAttributes[K] } & { [K in keyof XmasiarikovaBedApp & keyof XmasiarikovaBedAppAttributes as `prop:${K}`]?: XmasiarikovaBedApp[K] };
        "xmasiarikova-bed-editor": Omit<XmasiarikovaBedEditor, keyof XmasiarikovaBedEditorAttributes> & { [K in keyof XmasiarikovaBedEditor & keyof XmasiarikovaBedEditorAttributes]?: XmasiarikovaBedEditor[K] } & { [K in keyof XmasiarikovaBedEditor & keyof XmasiarikovaBedEditorAttributes as `attr:${K}`]?: XmasiarikovaBedEditorAttributes[K] } & { [K in keyof XmasiarikovaBedEditor & keyof XmasiarikovaBedEditorAttributes as `prop:${K}`]?: XmasiarikovaBedEditor[K] };
        "xmasiarikova-bed-list": Omit<XmasiarikovaBedList, keyof XmasiarikovaBedListAttributes> & { [K in keyof XmasiarikovaBedList & keyof XmasiarikovaBedListAttributes]?: XmasiarikovaBedList[K] } & { [K in keyof XmasiarikovaBedList & keyof XmasiarikovaBedListAttributes as `attr:${K}`]?: XmasiarikovaBedListAttributes[K] } & { [K in keyof XmasiarikovaBedList & keyof XmasiarikovaBedListAttributes as `prop:${K}`]?: XmasiarikovaBedList[K] };
        "xpaucof-hospital-app": Omit<XpaucofHospitalApp, keyof XpaucofHospitalAppAttributes> & { [K in keyof XpaucofHospitalApp & keyof XpaucofHospitalAppAttributes]?: XpaucofHospitalApp[K] } & { [K in keyof XpaucofHospitalApp & keyof XpaucofHospitalAppAttributes as `attr:${K}`]?: XpaucofHospitalAppAttributes[K] } & { [K in keyof XpaucofHospitalApp & keyof XpaucofHospitalAppAttributes as `prop:${K}`]?: XpaucofHospitalApp[K] };
        "xpaucof-visit-app": Omit<XpaucofVisitApp, keyof XpaucofVisitAppAttributes> & { [K in keyof XpaucofVisitApp & keyof XpaucofVisitAppAttributes]?: XpaucofVisitApp[K] } & { [K in keyof XpaucofVisitApp & keyof XpaucofVisitAppAttributes as `attr:${K}`]?: XpaucofVisitAppAttributes[K] } & { [K in keyof XpaucofVisitApp & keyof XpaucofVisitAppAttributes as `prop:${K}`]?: XpaucofVisitApp[K] };
        "xpaucof-visit-editor": Omit<XpaucofVisitEditor, keyof XpaucofVisitEditorAttributes> & { [K in keyof XpaucofVisitEditor & keyof XpaucofVisitEditorAttributes]?: XpaucofVisitEditor[K] } & { [K in keyof XpaucofVisitEditor & keyof XpaucofVisitEditorAttributes as `attr:${K}`]?: XpaucofVisitEditorAttributes[K] } & { [K in keyof XpaucofVisitEditor & keyof XpaucofVisitEditorAttributes as `prop:${K}`]?: XpaucofVisitEditor[K] };
        "xpaucof-visit-list": Omit<XpaucofVisitList, keyof XpaucofVisitListAttributes> & { [K in keyof XpaucofVisitList & keyof XpaucofVisitListAttributes]?: XpaucofVisitList[K] } & { [K in keyof XpaucofVisitList & keyof XpaucofVisitListAttributes as `attr:${K}`]?: XpaucofVisitListAttributes[K] } & { [K in keyof XpaucofVisitList & keyof XpaucofVisitListAttributes as `prop:${K}`]?: XpaucofVisitList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xmasiarikova-bed-app": LocalJSX.IntrinsicElements["xmasiarikova-bed-app"] & JSXBase.HTMLAttributes<HTMLXmasiarikovaBedAppElement>;
            "xmasiarikova-bed-editor": LocalJSX.IntrinsicElements["xmasiarikova-bed-editor"] & JSXBase.HTMLAttributes<HTMLXmasiarikovaBedEditorElement>;
            "xmasiarikova-bed-list": LocalJSX.IntrinsicElements["xmasiarikova-bed-list"] & JSXBase.HTMLAttributes<HTMLXmasiarikovaBedListElement>;
            "xpaucof-hospital-app": LocalJSX.IntrinsicElements["xpaucof-hospital-app"] & JSXBase.HTMLAttributes<HTMLXpaucofHospitalAppElement>;
            "xpaucof-visit-app": LocalJSX.IntrinsicElements["xpaucof-visit-app"] & JSXBase.HTMLAttributes<HTMLXpaucofVisitAppElement>;
            "xpaucof-visit-editor": LocalJSX.IntrinsicElements["xpaucof-visit-editor"] & JSXBase.HTMLAttributes<HTMLXpaucofVisitEditorElement>;
            "xpaucof-visit-list": LocalJSX.IntrinsicElements["xpaucof-visit-list"] & JSXBase.HTMLAttributes<HTMLXpaucofVisitListElement>;
        }
    }
}
